# Copyright (c) Sebastian Raschka under Apache License 2.0 (see LICENSE.txt)
# Source for "Build a Reasoning Model (From Scratch)": https://mng.bz/lZ5B
# Code repository: https://github.com/rasbt/reasoning-from-scratch

name: Test Nightly PyTorch

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '**/*.ipynb'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.sh'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.py'
      - '**/*.ipynb'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.sh'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  uv-tests:
    name: Code tests
    runs-on: ubuntu-latest
    env:
      SKIP_EXPENSIVE: "1"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python (uv)
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv and dependencies
        shell: bash
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync --group dev
          uv pip install -U --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu

      - name: Test reasoning_from_scratch package
        shell: bash
        run: |
          # uv run pytest tests
          # temporarily disabled
